services:
  backend:
    build:
      context: .  # Correctly set to src for backend service
      dockerfile: src/Dockerfile  # This points to ./src/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=neo4j://localhost:7687  # Use container name instead of localhost
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=mysecretpassword
    networks:
      - app-net

  frontend:
    build:
      context: .  # Correctly set to frontend for frontend service
      dockerfile: frontend/Dockerfile  # This points to ./frontend/Dockerfile
    ports:
      - "8501:8501"   # Streamlit default port
    environment:
      - API_BASE_URL=http://localhost:8000  # Use service name instead of localhost
    depends_on:
      - backend
    networks:
      - app-net

  neo4j:
    image: neo4j:latest
    container_name: neo4j-container
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
    environment:
      - NEO4J_AUTH=neo4j/mysecretpassword
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
